# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aef188c08b6f395cbe2e3193cddf3fa105252ca20f6f2abadbdd830afc7a84f1e77d9893329f53c0a550d33c51fc01bb1b3f1897d9e60d489ac91c1f0f842f6c

test:
  secret_key_base: 7a6f9bac4745b9e73411603510372788dc645e2f03a1f0fa3c98b98d224b36d3070e150c7f3d19bf7fc1413baafc7652c45ba930312072a20d9aa39e4f1c265c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
